services:
  kafka:
    image: bitnami/kafka:3.9.0
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_ENABLE_KRAFT=true
      - KAFKA_KRAFT_CLUSTER_ID=AAAAAAAAAAAAAAAAAAAAAA
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=IB
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,IB:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CONTROLLER://:9093,BROKER://:9092,IB://:9094
      - KAFKA_ADVERTISED_LISTENERS=BROKER://kafka:9092,IB://:9094
      - BITNAMI_DEBUG=yes
    restart: always

  grafana:
    image: grafana/grafana:9.4.3
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana/datasources-ch.yml:/etc/grafana/provisioning/datasources/datasources-ch.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  goflow2:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        VERSION: compose
        LDFLAGS: -X main.version=compose
    image: netsampler/goflow2
    depends_on:
      - kafka
    ports:
      - 8080:8080
      - 6343:6343/udp
      - 2055:2055/udp
    restart: always
    command:
      - -transport.kafka.brokers=kafka:9092
      - -transport=kafka
      - -transport.kafka.topic=flows
      - -format=bin

  db:
    image: clickhouse/clickhouse-server:24.11.1.2557-alpine
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./clickhouse:/docker-entrypoint-initdb.d/
      - ./clickhouse/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
      - ./clickhouse/protocols.csv:/var/lib/clickhouse/user_files/protocols.csv
    depends_on:
      - kafka

  superset:
    image: apache/superset:latest
    ports:
      - 8088:8088
    environment:
      - SUPERSET_SECRET_KEY=AVS9jBiie5xYz6trAQ20oNFri79C3T7QPIaNgDT79KqL1mhxuz+F2wwa
      - DATABASE_URL=clickhouse+http://default:@db:8123/default
    volumes:
      - ./superset:/app/pythonpath
    depends_on:
      - db
    restart: always

  risingwave:
    image: risingwavelabs/risingwave:latest
    ports:
      - 4566:4566
      - 5691:5691
    environment:
      - RW_BLOCK_CACHE_CAPACITY_MB=2048
      - RW_META_CACHE_CAPACITY_MB=2048
      - RW_SHARED_BUFFER_CAPACITY_MB=2048
      - RW_DEDICATED_RUNTIME=true
      - RW_TELEMETRY_TRACKING_ID=b95c30a9-e682-4aee-be85-527dc2472462
      - RW_IN_MEMORY_CACHE_CAPACITY_MB=2048
    restart: always

  jobmanager:
    image: flink:latest
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:latest
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=2

  flink-job:
    image: flink-kafka-clickhouse-job:latest
    depends_on:
      - jobmanager
      - taskmanager
      - kafka
      - db
